name: Deploy Cloud Function

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy Function
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Create zip archive
      run: |
        zip -r repository.zip .

    - name: Build and deploy Cloud Function
      run: |
        gcloud functions deploy testFunction \
          --runtime=Python3.9 \
          --region=us-central1 \
          --trigger-event-filters="type=google.pubsub.message.published" \
          --trigger-event-filters="attributes.topic='my-topic'" \
          --allow-unauthenticated \
          --trigger-http \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --no-gen2
