name: Deploy Cloud Function

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy Function
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Create zip archive
      run: |
        zip -r repository.zip .

    - name: Deploy Cloud Function
      uses: google-github-actions/deploy-cloud-functions@v2
      with:
        name: test-rest-function-lib  
        runtime: Python 3.9
        entry_point: hello
        memory_mb: 128  
        trigger: http 
        source: gs://test-repository-us-central1/repository.zip
